# ingress-red-yellow-hosts.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-nip-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: red.MINIKUBE_IP.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: red
            port:
              number: 80
  - host: yellow.MINIKUBE_IP.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yellow
            port:
              number: 80
